name: Nix Flake Check

on:
  push:
    branches: ["**"]
  pull_request:
  schedule:
    # 3AM, Sunday.
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run nix flake check
        run: nix flake check
